### ISSUE TITLE
Research whether to switch to WebGL (ditching deprecated Unity web player) or rewrite client using nw.js

### ISSUE THREAD

**Issue by Hoten** [Hoten/Gridia#10]
The browser world is ditching plugins, and so, we must say goodbye to the Unity web player. This presents a good opportunity to change the architecture/language of the client.

I'm weary of ditching Unity, only because it would mark the 6th (or so) major rewrite. Then again, I never really had a good reason to use Unity (besides cross platform building).

NW.JS would allow the client side to be written using web technologies, and still allow building to native executables. Programming directly for the web and compiling to native may be better than the other way around. It seems easier to create a user interface using HTML+CSS. There are weird sound bugs in the unity webplayer version, but WebGL may fix those. It may also be nice to simply server assets as html resources. That would greatly simplify the network protocol. 

Need to determine what html game engine to use. I would also like to use a language like Coffeescript in lieu of Javascript. Need to create a small prototype to see that all of the following can be accomplished:

* A nginx server which simply hosts resources (images, sounds, configs)
* Client grabs resources from server. Also, it updates when there are new resources. The HTTP caching protocols should take care of this
* Simple socket connection. Server merely sends a tick update every second, which would be some JSON for the client to process.
* Client generates a basic map and renders it
* Keyboard moves player
* Compile as native application, run in windows and linux
* Change data file, server notices, send new file out to clients
* Sfx
* inventory ui. Should be in html, but somehow also interact with the canvas

**Comment by Hoten** [comment]
I don't have time to do this. It seems it'd just be spinning a wheel, and I want to focus on progress. Should just move forward with what I got.

Will ignore a web version until Unity has better support for WebGL. The focus for the immediate future will be native clients.

**Comment by jordonias** [comment]
Looking forward to see more work on this. Keep us updated.
